name: attention
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.3
  - pytorch=1.11
  - torchvision
  - numpy=1.23
  - ipykernel
  - ipywidgets
  - google-colab
